### ISSUE TITLE
Missing database

### ISSUE THREAD

**Issue by kicholen** [Namek/TheConsole#1]
Exception in thread "LWJGL Application" java.lang.IllegalStateException: Value cannot be converted to string: object
        at com.badlogic.gdx.utils.JsonValue.asString(JsonValue.java:181)
        at net.namekdev.theconsole.commands.AliasManager.<init>(AliasManager.java:19)
        at net.namekdev.theconsole.TheConsole.create(TheConsole.java:114)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by Namek** [comment]
Oh, yeah, when `settings.db` is completely empty `JsonValue.asString()` can't create an empty string. Fixed by https://github.com/Namek/TheConsole/commit/7179c2dca960adb0a5f258cb1644c151e85dd154 Thanks!
